### ISSUE TITLE
Template was precompiled with an older version of Handlebars than the current runtime. Please update your precompiler to a newer version (>= 4.0.0) or downgrade your runtime to an older version (>= 2.0.0-beta.1)

### ISSUE THREAD

**Issue by Ryan-Miao** [federecio/dropwizard-swagger#100]
# Summary
We met error when using the library.

# OS environment
Windows 10 Chrome the latest version met the error below while Firefox and IE are OK.

# version
dropwizard version: `1.0.6`

swagger version
```xml
<dependency>
            <groupId>com.smoketurner</groupId>
            <artifactId>dropwizard-swagger</artifactId>
            <version>1.1.2-1</version>
</dependency>
```

```
Uncaught rdescription: undefinedfileName: undefinedlineNumber: undefinedmessage: "Template was precompiled with an older version of Handlebars than the current runtime. Please update your precompiler to a newer version (>= 4.0.0) or downgrade your runtime to an older version (>= 2.0.0-beta.1)."name: "Error"number: undefinedstack: "Error: Template was precompiled with an older version of Handlebars than the current runtime. Please update your precompiler to a newer version (>= 4.0.0) or downgrade your runtime to an older version (>= 2.0.0-beta.1).↵    at Object.s [as checkRevision] (http://localhost:8082/swagger-static/lib/handlebars-4.0.5.js:1:9353)↵    at Object.i [as template] (http://localhost:8082/swagger-static/lib/handlebars-4.0.5.js:1:10785)↵    at s.t.template (http://localhost:8082/swagger-static/lib/handlebars-4.0.5.js:1:1306)↵    at http://localhost:8082/swagger-static/swagger-ui.js:9:61↵    at http://localhost:8082/swagger-static/swagger-ui.js:24691:7"__proto__: Error
    at Object.<anonymous> (http://localhost:8082/swagger-static/lib/handlebars-4.0.5.js:1:4780)
    at e (http://localhost:8082/swagger-static/lib/handlebars-4.0.5.js:1:330)
    at Object.e.__esModule (http://localhost:8082/swagger-static/lib/handlebars-4.0.5.js:1:2019)
    at e (http://localhost:8082/swagger-static/lib/handlebars-4.0.5.js:1:330)
    at Object.e.default.e (http://localhost:8082/swagger-static/lib/handlebars-4.0.5.js:1:1385)
    at e (http://localhost:8082/swagger-static/lib/handlebars-4.0.5.js:1:330)
    at Object.e.default.t.__esModule.default (http://localhost:8082/swagger-static/lib/handlebars-4.0.5.js:1:742)
    at e (http://localhost:8082/swagger-static/lib/handlebars-4.0.5.js:1:330)
    at http://localhost:8082/swagger-static/lib/handlebars-4.0.5.js:1:417
    at http://localhost:8082/swagger-static/lib/handlebars-4.0.5.js:1:422
swagger:45 Uncaught ReferenceError: SwaggerUi is not defined
    at HTMLDocument.<anonymous> (swagger:45)
    at k (jquery-1.8.0.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.8.0.min.js:2)
    at Function.ready (jquery-1.8.0.min.js:2)
    at HTMLDocument.D (jquery-1.8.0.min.js:2)
```

**Comment by Ryan-Miao** [comment]
Find the same issue, https://github.com/smoketurner/dropwizard-swagger/issues/73
