### ISSUE TITLE
Dropwizard 0.8.1, Swagger 1.5, instantiationError: com.wordnik.swagger.config.SwaggerConfig

### ISSUE THREAD

**Issue by chriskessel** [federecio/dropwizard-swagger#57]
```
    BeanConfig swaggerConfig = new BeanConfig();
    swaggerConfig.setVersion("2.0"); // This is the swagger version?
    swaggerConfig.setResourcePackage("com.kessel");
    swaggerConfig.setScan(true);
    swaggerConfig.setBasePath(".." + environment.getApplicationContext().getContextPath());
```

Results in this stack trace:

```
    Exception in thread "main" java.lang.InstantiationError: com.wordnik.swagger.config.SwaggerConfig
at com.wordnik.swagger.config.ConfigFactory$.<init>(ConfigFactory.scala:7)
at com.wordnik.swagger.config.ConfigFactory$.<clinit>(ConfigFactory.scala)
at com.wordnik.swagger.jaxrs.config.BeanConfig.<init>(BeanConfig.scala:26)
```

I've got the following two dependencies in gradle. That should be sufficient, yes?

```
compile group: "com.wordnik", name: "swagger-jersey-jaxrs_2.10", version: "1.3.12"
compile group: "com.wordnik", name: "swagger-core", version: "1.5.3-M1"
```

**Comment by chriskessel** [comment]
Doh! Wrong repo (cut/paste to wrong window). Sorry.
