### ISSUE TITLE
Add support for dropwizard 0.8.1

### ISSUE THREAD

**Issue by silvpol** [federecio/dropwizard-swagger#64]
When using dropwizard-swagger with dropwizard 0.8.1 I get following exception on startup:

Exception in thread "main" java.lang.AbstractMethodError
    at io.dropwizard.views.ViewBundle.run(ViewBundle.java:112)
    at io.dropwizard.views.ViewBundle.run(ViewBundle.java:92)
    at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:183)
    at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:41)
    at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76)
    at io.dropwizard.cli.Cli.run(Cli.java:70)
    at io.dropwizard.Application.run(Application.java:73)
    at ibid.server.portal.PortalService.main(PortalService.java:50)

This seems to be a dependency issue - rebuilding dropwizard-swagger against 0.8.1 and disabling maven-enforcer-plugin (dropwizard-junit depends on 0.8.0 and fails build) allows to start without problem.

**Comment by jplock** [comment]
I submitted a PR to upgrade to Dropwizard 0.8.2 https://github.com/federecio/dropwizard-swagger/pull/63

**Comment by m-manu** [comment]
@federecio Can you please release 'Swagger for Dropwizard 0.8.2' to Maven Central? Thanks.

**Comment by m-manu** [comment]
@federecio Are you planning to continue to maintain this repo?
